In [1]:
import warnings
warnings.filterwarnings(action='ignore')

In [2]:
import pandas as pd
import numpy as np
import requests

# Create DataFrame

In [3]:
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=1')

In [4]:
response

<Response [200]>

In [5]:
response.json()

{'page': 1,
 'results': [{'adult': False,
   'backdrop_path': '/tmU7GeKVybMWFButWEGl2M4GeiP.jpg',
   'genre_ids': [18, 80],
   'id': 238,
   'original_language': 'en',
   'original_title': 'The Godfather',
   'overview': 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.',
   'popularity': 132.488,
   'poster_path': '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
   'release_date': '1972-03-14',
   'title': 'The Godfather',
   'video': False,
   'vote_average': 8.7,
   'vote_count': 18602},
  {'adult': False,
   'backdrop_path': '/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg',
   'genre_ids': [18, 80],
   'id': 278,
   'original_language': 'en',
   'original_title': 'The Shawshank Redemption',
   'overview': 'Framed in the 1940s for the double murder of his

In [6]:
df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]

In [7]:
df.head(2)

id                     title  \
0  238             The Godfather   
1  278  The Shawshank Redemption   

                                            overview release_date  popularity  \
0  Spanning the years 1945 to 1955, a chronicle o...   1972-03-14     132.488   
1  Framed in the 1940s for the double murder of h...   1994-09-23     104.251   

   vote_average  vote_count  
0           8.7       18602  
1           8.7       24560

In [8]:
df = pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [9]:
for i in range(1,429):
    response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page={}'.format(i))
    temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
    df = df.append(temp_df,ignore_index=True)


In [10]:
df.head()

id                        title  \
0    238                The Godfather   
1    278     The Shawshank Redemption   
2    240        The Godfather Part II   
3    424             Schindler's List   
4  19404  Dilwale Dulhania Le Jayenge   

                                            overview release_date  popularity  \
0  Spanning the years 1945 to 1955, a chronicle o...   1972-03-14     132.488   
1  Framed in the 1940s for the double murder of h...   1994-09-23     104.251   
2  In the continuing saga of the Corleone crime f...   1974-12-20      65.488   
3  The true story of how businessman Oskar Schind...   1993-12-15      88.117   
4  Raj is a rich, carefree, happy-go-lucky second...   1995-10-20      25.025   

   vote_average  vote_count  
0           8.7       18602  
1           8.7       24560  
2           8.6       11236  
3           8.6       14518  
4           8.6        4240

In [11]:
df.shape

(8560, 7)

# Data Cleaning

In [12]:
df.isnull().sum()

id              0
title           0
overview        0
release_date    0
popularity      0
vote_average    0
vote_count      0
dtype: int64

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8560 entries, 0 to 8559
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   id            8560 non-null   int64  
 1   title         8560 non-null   object 
 2   overview      8560 non-null   object 
 3   release_date  8560 non-null   object 
 4   popularity    8560 non-null   float64
 5   vote_average  8560 non-null   float64
 6   vote_count    8560 non-null   int64  
dtypes: float64(2), int64(2), object(3)
memory usage: 468.2+ KB


In [14]:
df.to_csv('movies.csv')

In [15]:
df.head()

id                        title  \
0    238                The Godfather   
1    278     The Shawshank Redemption   
2    240        The Godfather Part II   
3    424             Schindler's List   
4  19404  Dilwale Dulhania Le Jayenge   

                                            overview release_date  popularity  \
0  Spanning the years 1945 to 1955, a chronicle o...   1972-03-14     132.488   
1  Framed in the 1940s for the double murder of h...   1994-09-23     104.251   
2  In the continuing saga of the Corleone crime f...   1974-12-20      65.488   
3  The true story of how businessman Oskar Schind...   1993-12-15      88.117   
4  Raj is a rich, carefree, happy-go-lucky second...   1995-10-20      25.025   

   vote_average  vote_count  
0           8.7       18602  
1           8.7       24560  
2           8.6       11236  
3           8.6       14518  
4           8.6        4240

In [16]:
df.duplicated().sum()

0

In [17]:
df.drop_duplicates(keep='first', inplace=True)

In [18]:
df.duplicated().sum()

0

In [19]:
df.shape

(8560, 7)

In [20]:
df['overview'][0]

'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.'

In [21]:
df['overview'].apply(lambda x: x.split())

0       [Spanning, the, years, 1945, to, 1955,, a, chr...
1       [Framed, in, the, 1940s, for, the, double, mur...
2       [In, the, continuing, saga, of, the, Corleone,...
3       [The, true, story, of, how, businessman, Oskar...
4       [Raj, is, a, rich,, carefree,, happy-go-lucky,...
                              ...                        
8555    [The, Griswold, family, hits, the, road, again...
8556    [Max, and, Page, are, a, brilliant, mother/dau...
8557    [Once, upon, a, time..., in, the, far, away, k...
8558    [Looking, for, an, escape, from, her, recurrin...
8559    [After, waking, up, in, a, hospital, with, amn...
Name: overview, Length: 8560, dtype: object

In [22]:
df['overview'] = df['overview'].apply(lambda x: x.split())

In [23]:
df.head(2)

id                     title  \
0  238             The Godfather   
1  278  The Shawshank Redemption   

                                            overview release_date  popularity  \
0  [Spanning, the, years, 1945, to, 1955,, a, chr...   1972-03-14     132.488   
1  [Framed, in, the, 1940s, for, the, double, mur...   1994-09-23     104.251   

   vote_average  vote_count  
0           8.7       18602  
1           8.7       24560

In [24]:
new_df = df.copy()

In [25]:
new_df['overview'].apply(lambda x:' '.join(x)) 

0       Spanning the years 1945 to 1955, a chronicle o...
1       Framed in the 1940s for the double murder of h...
2       In the continuing saga of the Corleone crime f...
3       The true story of how businessman Oskar Schind...
4       Raj is a rich, carefree, happy-go-lucky second...
                              ...                        
8555    The Griswold family hits the road again for a ...
8556    Max and Page are a brilliant mother/daughter c...
8557    Once upon a time... in the far away kingdom of...
8558    Looking for an escape from her recurring night...
8559    After waking up in a hospital with amnesia, pr...
Name: overview, Length: 8560, dtype: object

In [26]:
new_df['overview'] = new_df['overview'].apply(lambda x:' '.join(x)) 

In [27]:
new_df.head(2)

id                     title  \
0  238             The Godfather   
1  278  The Shawshank Redemption   

                                            overview release_date  popularity  \
0  Spanning the years 1945 to 1955, a chronicle o...   1972-03-14     132.488   
1  Framed in the 1940s for the double murder of h...   1994-09-23     104.251   

   vote_average  vote_count  
0           8.7       18602  
1           8.7       24560

In [28]:
new_df['overview'].apply(lambda x: x.lower())

0       spanning the years 1945 to 1955, a chronicle o...
1       framed in the 1940s for the double murder of h...
2       in the continuing saga of the corleone crime f...
3       the true story of how businessman oskar schind...
4       raj is a rich, carefree, happy-go-lucky second...
                              ...                        
8555    the griswold family hits the road again for a ...
8556    max and page are a brilliant mother/daughter c...
8557    once upon a time... in the far away kingdom of...
8558    looking for an escape from her recurring night...
8559    after waking up in a hospital with amnesia, pr...
Name: overview, Length: 8560, dtype: object

In [29]:
new_df['overview'] = new_df['overview'].apply(lambda x: x.lower())

In [30]:
new_df['overview'][0]

'spanning the years 1945 to 1955, a chronicle of the fictional italian-american corleone crime family. when organized crime family patriarch, vito corleone barely survives an attempt on his life, his youngest son, michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.'

In [31]:
import nltk

In [32]:
from nltk.stem.porter import PorterStemmer

In [33]:
ps = PorterStemmer()

In [34]:
def stem(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))
    return ' '.join(y)

In [35]:
stem(new_df['overview'][0])

'span the year 1945 to 1955, a chronicl of the fiction italian-american corleon crime family. when organ crime famili patriarch, vito corleon bare surviv an attempt on hi life, hi youngest son, michael step in to take care of the would-b killers, launch a campaign of bloodi revenge.'

In [36]:
new_df['overview'] = new_df['overview'].apply(stem)

In [37]:
new_df['overview']

0       span the year 1945 to 1955, a chronicl of the ...
1       frame in the 1940 for the doubl murder of hi w...
2       in the continu saga of the corleon crime famil...
3       the true stori of how businessman oskar schind...
4       raj is a rich, carefree, happy-go-lucki second...
                              ...                        
8555    the griswold famili hit the road again for a t...
8556    max and page are a brilliant mother/daught con...
8557    onc upon a time... in the far away kingdom of ...
8558    look for an escap from her recur nightmares, 1...
8559    after wake up in a hospit with amnesia, profes...
Name: overview, Length: 8560, dtype: object

# Creating Model

In [38]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000, stop_words='english')

In [39]:
cv.fit_transform(new_df['overview']).toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [40]:
cv.fit_transform(new_df['overview']).toarray().shape

(8560, 5000)

In [41]:
vectors = cv.fit_transform(new_df['overview']).toarray()

In [42]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [43]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0])

In [44]:
cv.get_feature_names_out()

array(['000', '10', '100', ..., 'zombies', 'zone', 'zoo'], dtype=object)

In [45]:
len(cv.get_feature_names_out())

5000

In [47]:
from sklearn.metrics.pairwise import cosine_similarity

In [48]:
cosine_similarity(vectors)

array([[1.        , 0.21726205, 0.24618298, ..., 0.11149893, 0.04494666,
        0.        ],
       [0.21726205, 1.        , 0.03268602, ..., 0.19985202, 0.03580574,
        0.        ],
       [0.24618298, 0.03268602, 1.        , ..., 0.        , 0.06085806,
        0.        ],
       ...,
       [0.11149893, 0.19985202, 0.        , ..., 1.        , 0.04134491,
        0.04622502],
       [0.04494666, 0.03580574, 0.06085806, ..., 0.04134491, 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.04622502, 0.        ,
        1.        ]])

In [49]:
cosine_similarity(vectors).shape

(8560, 8560)

In [50]:
similarity = cosine_similarity(vectors)

In [51]:
similarity

array([[1.        , 0.21726205, 0.24618298, ..., 0.11149893, 0.04494666,
        0.        ],
       [0.21726205, 1.        , 0.03268602, ..., 0.19985202, 0.03580574,
        0.        ],
       [0.24618298, 0.03268602, 1.        , ..., 0.        , 0.06085806,
        0.        ],
       ...,
       [0.11149893, 0.19985202, 0.        , ..., 1.        , 0.04134491,
        0.04622502],
       [0.04494666, 0.03580574, 0.06085806, ..., 0.04134491, 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.04622502, 0.        ,
        1.        ]])

In [60]:
sorted(list(enumerate(similarity[0])), reverse=True, key=lambda x:x[1])[1:6]

[(1271, 0.3721200626209055),
 (6614, 0.3692744729379982),
 (5548, 0.3503245248726854),
 (879, 0.34401397986945004),
 (1721, 0.33213950328512926)]

In [61]:
def recommend(movie):
    movie_index = new_df[new_df['title'] == movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x:x[1])[1:6]
    for i in movies_list:
        print(i[0])
    return 

In [66]:
recommend('Batman')

844
4722
865
9
3759


In [71]:
new_df.iloc[3759]

id                                                          20077
title                                      The Batman vs. Dracula
overview        gotham citi is terror not onli by recent escap...
release_date                                           2005-10-18
popularity                                                 12.908
vote_average                                                  7.0
vote_count                                                    301
Name: 3759, dtype: object